### ISSUE TITLE
Kernel expects sqlite3 to be installed

### ISSUE THREAD

**Issue by stephanemmer** [brownan/sqlite3-kernel#5]
Hi,

thank you for this great project, we use the kernel a lot.
When I was trying to add the kernel in a docker container, I was stumbling about the fact that the sqlite3 library needs to be installed separately.

Can you please add this small hint to the Readme file? This might help some people when troubleshooting.

Thanks a lot!

**Comment by brownan** [comment]
Good idea, thanks!
